services:
    web:
        container_name: web-spam-iota
        build:
            context: ..
            dockerfile: docker/web/Dockerfile
        ports:
            - '8080:80'
        networks:
            - web

networks:
    web:
        external: true
